### ISSUE TITLE
benchcodecs.py issues

### ISSUE THREAD

**Issue by gakabani** [NeuroJSON/pyjdata#5]
This is the following issue while running benchcodecs.py 
I am running on Python 3.11.5
```
Traceback (most recent call last):
  File "/Users/gamalakabani/Codes/pyjdata/pyjdata-master/test/benchcodecs.py", line 67, in <module>
    res = list(map(benchmark, codecs, [x] * len(codecs)))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gamalakabani/Codes/pyjdata/pyjdata-master/test/benchcodecs.py", line 41, in benchmark
    jd.save(x, "matrix_" + codec + ext, {"compression": codec, "nthread": nthread})
  File "/Users/gamalakabani/miniconda3/lib/python3.11/site-packages/jdata/jfile.py", line 95, in save
    saveb(data, fname, opt, **kwargs)
  File "/Users/gamalakabani/miniconda3/lib/python3.11/site-packages/jdata/jfile.py", line 304, in saveb
    data = jd.encode(data, opt)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/gamalakabani/miniconda3/lib/python3.11/site-packages/jdata/jdata.py", line 201, in encode
    newobj["_ArrayZipData_"] = blosc2.compress2(
                               ^^^^^^^^^^^^^^^^^
  File "/Users/gamalakabani/miniconda3/lib/python3.11/site-packages/blosc2/core.py", line 1325, in compress2
    return blosc2_ext.compress2(src, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "blosc2_ext.pyx", line 749, in blosc2.blosc2_ext.compress2
  File "blosc2_ext.pyx", line 689, in blosc2.blosc2_ext.create_cparams_from_kwargs
NameError: `compcode` has been renamed to `codec`.  Please go update your code.
```
Any help will be appreciated.

**Comment by fangq** [comment]
@gakabani, thanks for reporting this. the complained blosc2 option name has been updated.

@FrancescAlted: after making this change, I am still getting an error 

https://github.com/NeuroJSON/pyjdata/actions/runs/10329100584/job/28596633348

```
  File "blosc2_ext.pyx", line 1, in init blosc2.blosc2_ext
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

do you know what might have caused this?

**Comment by FrancescAlted** [comment]
This is probably due to the fact that latest version of python-blosc2 has been compiled with NumPy 2.0.  You would need to use a more recent version of it (>=1.23).

**Comment by gakabani** [comment]
Dr. Fang, I sent you an email requesting your help.
